apiVersion: v1
kind: Service
metadata:
  name: zoomcamp-model
spec:
  type: LoadBalancer
  selector:
    app: subscription
  ports:
  - port: 80                # The port used in browser/API client
    targetPort: 8080        # The port uvicorn is listening on (from Dockerfile)